config/routes.rb
Rails.application.routes.draw do

  namespace :profile do
    resources :users, only: :show
  end

  get 'dashboards/show'

  devise_for :users,
    controllers: {
                    omniauth_callbacks: 'users/omniauth_callbacks',
                    registrations: 'registrations'
                 }

  resources :meetings do
    resources :bookings do
      member do
        patch "confirm_user"
      end
    end
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  has_many :booking

  geocoded_by :local
  after_validation :geocode

  validates :title, presence: true
  validates :description, presence: true
  validates :nb_max_participant, presence: true, :inclusion => { :in => 1..5 }
  validates :local, presence: true
  validates :date, presence: true
  validate :future_event


  # method for seach
  def self.search(search)
    where("title ILIKE (?) OR description ILIKE (?)", "%#{search}%", "%#{search}%")
    # where("description ILIKE ?", "%#{search}%")
  end

  private

  def future_event
    errors.add(:date, "You can't create a meeting in the past. People can't time travel yet.") if date <= Time.now
  end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  def index
    @meetings = Meeting.all
    if params[:search]
      @meetings = Meeting.search(params[:search]).order("date ASC").where('date >= ?', Time.now)
    else
      @meetings = Meeting.all.order('date ASC').where('date >= ?', Time.now)
    end
  end

  def show
    @user = current_user
    @mentor = @meeting.user
    @user == @mentor ? @show_mentees = true : @show_mentees = false

    @booking = @user.booking.where(meeting_id: @meeting.id)[0]
  end

  def new
    @meeting = Meeting.new
  end

  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.user = current_user
    if @meeting.save
      redirect_to meetings_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @meeting.update_attributes(meeting_params)
    redirect_to meeting_path(@meeting)
  end

  def destroy
    @meeting.destroy
    redirect_to dashboards_show_path
  end

  private

  def meeting_params
    params.require(:meeting).permit(:title, :description, :date, :local, :nb_max_participant, :profile_wanted)
  end

  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

end

app/helpers/meetings_helper.rb
module MeetingsHelper
    INDUSTRY_IMAGES = {
      "Accommodations" => 'https://static.pexels.com/photos/308/hotel-sign-neon-letters.jpg',
      "Accounting" => "https://static.pexels.com/photos/53621/calculator-calculation-insurance-finance-53621.jpeg",
      "Animation" => "https://static.pexels.com/photos/34639/pexels-photo.jpg",
       "Aerospace" => "https://static.pexels.com/photos/34521/space-shuttle-lift-off-liftoff-nasa.jpg",
       "Agriculture & Agribusiness" => "https://static.pexels.com/photos/106162/wheat-wheat-spike-wheat-field-cornfield-106162.jpeg",
       "Air Transportation" => "https://static.pexels.com/photos/195477/pexels-photo-195477.jpeg",
       "Apparel & Accessories" => "https://static.pexels.com/photos/135620/pexels-photo-135620.jpeg",
       "Auto" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Banking" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Beauty & Cosmetics" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Biotechnology" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Chemical" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Communications" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Computer Software" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Construction" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Consulting" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Consumer Products" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Education" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Electronics" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Employment" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Energy" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Entertainment" => "https://static.pexels.com/photos/196643/pexels-photo-196643.jpeg",
       "Fashion" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Financial Services" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Fine Arts" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Food & Beverage" => "https://static.pexels.com/photos/196643/pexels-photo-196643.jpeg",
       "Green Technology" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Health" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Information" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Information Technology" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Insurance" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Journalism & News" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Legal Services" => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Manufacturing"  => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Media & Broadcasting"  => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Medical Devices & Supplies"  => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Motion Pictures & Video"  => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Music"  => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Pharmaceutical"  => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Public Administration"  => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Public Relations"  => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Publishing"  => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Rail"  => 'https://static.pexels.com/photos/308/hotel-sign-neon-letters.jpg',
       "Real Estate"  => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Retail"  => 'https://static.pexels.com/photos/5698/healthy-market-shop-eco.jpg',
       "Service"  => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Sports"  => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Technology"  => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Telecommunications"  => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Tourism"  => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Transportation/Trucking/Railroad"  => "https://static.pexels.com/photos/5117/people-feet-train-travelling.jpeg",
       "Travel"  => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Utilities"  => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Video Game"  => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",
       "Web Services"  => "https://static.pexels.com/photos/239898/pexels-photo-239898.jpeg",

    }


  # def avatar_url?(user)
  #    if user.avatar_url.present?
  #       user.avatar_url
  #    else
  #     #  image_path('avatar-placeholder.png')
  #      "https://api.adorable.io/avatars/100/abott@adorable.io.png "
  #    end
  # end

  def set_industry_image(user)
      if user.industry.present?
      url = INDUSTRY_IMAGES[user.industry]
    else
      'https://static.pexels.com/photos/53621/calculator-calculation-insurance-finance-53621.jpeg'
    end
  end
end

app/views/meetings/_form.html.erb
<%= simple_form_for(@meeting) do |f| %>
  <%= f.error_notification %>
    <%= f.input :title, placeholder: "" %>
    <%= f.input :description, placeholder: "" %>
    <%= f.input :nb_max_participant, placeholder: "From 1 to 5", collection: 1..5 %>
    <%= f.input :profile_wanted, label: 'Level of Experience', collection: User::PROFILE %>
    <%= f.input :date, placeholder: "", class: 'datepicker' %>
    <%= f.input :local, placeholder: "" %>
    <%= f.button :submit, class: "btn btn-primary"  %>
<% end %>

app/views/meetings/_meetings.html.erb
<div class="row">
    <% meetings.each do |m| %>
    <div class="col-md-6 col-lg-4">
        <div class="card card-meeting">
            <!-- <div class="header-image" background="https://unsplash.it/1200/800" alt=""></div> -->
            <!-- # <div class="header-image" style="background-image: url('https://unsplash.it/900/800')"></div> -->
            <div class="header-image" style="background-image: url(<%= set_industry_image(m.user) %>)"></div>

            <%= link_to profile_user_path(m.user) do %>
            <div class='div-center'><%= image_tag m.user.avatar_url, class: 'header-avatar' %></div>
            <% end %>

            <div class="content text-center">
                <h4><%= m.user.first_name %>
                    <%= m.user.last_name %></h4>
                <h6><%= m.user.industry %>
                    <%= m.user.profile %></h6>
                <hr>
                <%= link_to meeting_path(m) do %>
                <h3><%= m.title.first(30) %></h3>
                <p><%= m.description.first(140) %></p>
                <% end %>
                <hr>
                <p>
                    <i class="fa fa-calendar"></i>
                    <%= m.date.strftime("%d %b, %Y") %> - <%= m.date.strftime("%I:%M%P") %></p>
                <p>
                    <i class="fa fa-map-marker"></i>
                    <%= m.local %></p>
                <div class="btn-card-position"><%= link_to 'Join', new_meeting_booking_path(m), class: 'btn btn-primary' %></div>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/meetings/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h2>Edit your Meeting</h2>
      <%= simple_form_for(@meeting) do |f| %>
        <%= f.error_notification %>
          <%= f.input :title, placeholder: "", :readonly => true %>
          <%= f.input :description, placeholder: "", :readonly => true %>
          <%= f.input :nb_max_participant, placeholder: "From 1 to 5", collection: 1..5, :disabled => true %>
          <%= f.input :profile_wanted, label: 'Level of Experience', collection: User::PROFILE, :disabled => true %>
          <%= f.input :date, placeholder: "" %>
          <%= f.input :local, placeholder: "" %>
          <%= f.button :submit, class: "btn btn-primary"  %>
      <% end %>
      <br>
    <%= link_to 'Back', meeting_path(@meeting) %>
    </div>
  </div>
</div>

app/views/meetings/index.html.erb
<div class="container">
<h1 class="text-center padded-top">Choose one of the <%= Meeting.all.order('date ASC').where('date >= ?', Time.now).count %> meetings available. </h1>
<h4 class="text-center padded-bottom">Just a very powerful phrase that will make people crazy about MentorIn</h4>
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 text-center padded-bottom">
    <%= form_tag(meetings_path, :method => "get", id: "search-form", class: "form-inline") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search", class: 'form-control' %>
      <%= submit_tag "Search", class: 'btn btn-info' %>
    <% end %>
    </div>
  </div>
  <% if @meetings.present? %>
    <%= render 'meetings', meetings: @meetings %>
  <% else %>
    <p class="padded text-center text-warning bg-warning">There are no <strong>Meetings</strong> containing the term(s) <%= params[:search] %>.</p>
  <% end %>
</div>

app/views/meetings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h2>New Meeting</h2>
      <%= render 'form' %>
      <br>
      <%= link_to 'Back', meetings_path, class: 'btn btn-default' %>
    </div>
  </div>
</div>

  <script src="https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=AIzaSyCmMFuw1p_sdIYAPZjnN8ts_41FZXkXOnw"></script>

app/views/meetings/show.html.erb
<div class="container">
<!-- card with the mentor profile on the side -->
  <div class="row">

    <div class="col-xs-3" >
      <div class="text-center card card-profile">
        <div class="header-image" style="background-image: url('https://unsplash.it/600/120')"></div>
        <%= link_to profile_user_path(@meeting.user) do %>
          <div class='div-center'><%= image_tag @meeting.user.avatar_url%></div>
        <% end %>
        <div class="content text-center">
          <h4><%= "#{@meeting.user.first_name} #{@meeting.user.last_name}"%></h4><br>
          <h6><%=@meeting.user.industry%></h6>
          <h6><%=@meeting.user.profile %></h6>
        </div>
      </div>

    </div>

    <div class="col-xs-9">
      <div class="card card-profile">
        <div class="row">
        <div class="col-xs-12">
        <div class="padded-left">
          <h2><%= @meeting.title %></h2>
          <p><%= @meeting.description %></p>
          <hr>
        </div>
        </div>
        </div>

      <div class="row margin-bottom">
        <div class="col-xs-6">
        <div class="padded-left">
          <p><i class="fa fa-calendar"></i><%=" #{@meeting.date.strftime('%d %b, %Y')}"%> | <i class="fa fa-clock-o"></i><%=" #{@meeting.date.strftime('%I:%M%P')}"%></p>
          <p><i class="fa fa-map-marker"></i><%=" #{@meeting.local}"%></p>
          <p><i class="fa fa-user" aria-hidden="true"></i><%=" Profiles: #{@meeting.profile_wanted}  |  Max. participants: #{@meeting.nb_max_participant}"%></p>
        </div>
        </div>

        <div class="col-xs-6">
        <div class="relative">
          <div class="absolute-position">
            <!-- if meeting of the current user -->
            <%if @show_mentees && @meeting.booking.count>0%>
                <%= link_to edit_meeting_path(@meeting) do %><i class="fa fa-pencil-square-o" aria-hidden="true"></i><% end %>&nbsp
                <%= link_to meeting_path, method: :delete, data: { confirm: "Are you sure? Please do inform the Attendees" } do %><i class="fa fa-trash-o" aria-hidden="true"></i><% end %>
            <% else %>
              <!-- status and button depending on current_user -->
              <% if @booking%>
                <% if @booking.confirmation%>
                  <h6><%= image_tag 'green-light.png', id: "light"%>Your participation has been confirmed</h6>
                <% else %>
                  <h6><%= image_tag 'red-light.png', id: "light"%>Confirmation for your participation pending</h6>
                <% end %>
              <% else %>
                <%= link_to "Join", new_meeting_booking_path(@meeting), class: "btn btn-success" %>
              <% end %>
            <% end %>
          </div>
        </div>
        </div>

      </div>
      </div>
    </div>

  </div>

  <div class="row">
    <div class="col-xs-12">
        <div class="text-center card card-map">
        <div class="map-wrapper">
        <div id="map" style="width: 100%; height: 200px;"></div>
        </div>
        </div>
    </div>
  </div>

<%if @show_mentees #display the list of booking only to the mentor%>
<div class="row">
  <div class="col-xs-12 text-center">
    <h3>List of participation request for your mentorship</h3>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
  <div class="card card-list">
    <hr>
    <%@meeting.booking.order(:id).each do |booking|%>
    <div class="row list-div">
      <div class="col-xs-4">
        <div class="dash-flex">
          <div class='div-center'>
            <%= image_tag booking.user.avatar_url, class: "dash-avatar"%>
          </div>
          <div class="dash-title">
           <%="#{booking.user.first_name} #{booking.user.last_name}"%><br>
            <h6><%="#{booking.user.profile} | #{booking.user.industry}"%></h6>
          </div>
        </div>
      </div>

      <div class="col-xs-6">
        <%="Motivations: #{booking.motivations}" %>
      </div>

      <div class="col-xs-2 text-center">
        <% if booking.confirmation %>
          <h6>Participant confirmed</h6>
            <%= image_tag 'green-light.png', id: "light"%>
        <% else %>
        <%= button_to "Confirm participation", confirm_user_meeting_booking_path(@meeting,booking), method: :patch, class: "btn btn-success text-btn" %>
        <% end %>
      </div>
    </div>
    <hr>
    <% end %>
  </div>
  </div>
</div>
<% end %>


</div>


  <%= javascript_tag do %>

  function initMap() {
        var uluru = {lat: <%= @meeting.latitude %>, lng: <%= @meeting.longitude %>};
        var map = new google.maps.Map(document.getElementById('map'), {
          styles: [{"featureType":"administrative","elementType":"all","stylers":[{"visibility":"on"},{"lightness":33}]},{"featureType":"landscape","elementType":"all","stylers":[{"color":"#f2e5d4"}]},{"featureType":"poi.park","elementType":"geometry","stylers":[{"color":"#c5dac6"}]},{"featureType":"poi.park","elementType":"labels","stylers":[{"visibility":"on"},{"lightness":20}]},{"featureType":"road","elementType":"all","stylers":[{"lightness":20}]},{"featureType":"road.highway","elementType":"geometry","stylers":[{"color":"#c5c6c6"}]},{"featureType":"road.arterial","elementType":"geometry","stylers":[{"color":"#e4d7c6"}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"color":"#fbfaf7"}]},{"featureType":"water","elementType":"all","stylers":[{"visibility":"on"},{"color":"#acbcc9"}]}],
          zoom: 14,
          center: uluru,
          mapTypeControl: false,
          scrollwheel: false
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
      }
<% end %>
<script async defer src="https://maps.google.com/maps/api/js?key=<%= ENV['GOOGLE_API_BROWSER_KEY'] %>&callback=initMap"></script>
  </div>