config/routes.rb
Rails.application.routes.draw do

  namespace :profile do
    resources :users, only: :show
  end

  get 'dashboards/show'

  devise_for :users,
    controllers: {
                    omniauth_callbacks: 'users/omniauth_callbacks',
                    registrations: 'registrations'
                 }

  resources :meetings do
    resources :bookings do
      member do
        patch "confirm_user"
      end
    end
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="navbar-wagon-left">
    <div>
      <% if current_user %>
      <%= link_to 'MentorIn', meetings_path, class: "navbar-wagon-brand" %>
      <% else %>
      <%= link_to 'MentorIn', root_path, class: "navbar-wagon-brand" %>
      <% end %>
    </div>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
  <% if user_signed_in? %>

    <!-- Button (call-to-action) -->
    <div class="text-center navbar-text navbar-righ">
      <%= link_to new_meeting_path, class: "navbar-icone" do %>
          <p class="navbar-text navbar-left"><i class="fa fa-users"></i><br>
         Create Meeting&nbsp;&nbsp;&nbsp;</p>
      <% end %>
      <%= link_to meetings_path, class: "navbar-icone" do %>
          <p class="navbar-text navbar-left"><i class="fa fa-th-list"></i><br>
         View Meetings&nbsp;&nbsp;&nbsp;</p>
      <% end %>
      <%= link_to dashboards_show_path, class: "navbar-icone" do %>
          <p class="navbar-text navbar-left"><i class="fa fa-user"></i><br>
         Dashboard&nbsp;&nbsp;&nbsp;</p>
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete, class: "navbar-icone" do  %>
          <p class="navbar-text navbar-left"><i class="fa fa-sign-out"></i><br>
         Log out</p>
      <% end %>
    </div>



      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= link_to profile_user_path(current_user) do %>
          <%= image_tag current_user.avatar_url, class: "avatar-large dropdown-toggle", id: "navbar-wagon-menu" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
<!-- link to add below destroy_user_session_path -->
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

<!-- add if user not logged in -->
      <% else %>
      <p class="navbar-text navbar-right"><%= link_to 'Sign in / Sign up', '#myModal', data: {toggle: "modal"}, class: "navbar-icone" %></p>
      <!-- Button trigger modal -->
      <% end %>

    <!-- modal for Log in -->
    <% unless current_user %>
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header text-center">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Log in</h4>
            </div>
            <div class="modal-body">
              <%= render 'devise/sessions/new'%>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">

      <!-- <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i> -->
      <% if user_signed_in? %>
        <!-- <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i> -->
        <%= image_tag current_user.avatar_url, class: "avatar-large dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to new_meeting_path do %>
            <i class="fa fa-users"></i> Create Meeting
        <% end %></li>
        <li><%= link_to meetings_path do %>
            <i class="fa fa-th-list"></i> View Meetings
        <% end %></li>
        <li><%= link_to dashboards_show_path do %>
            <i class="fa fa-user"></i> Dashboard
        <% end %></li>
        <li><%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
        <% end %></li>
      </ul>
      <% else %>

      <span class="hidden-xs"><%= link_to 'Sign in / Sign up',new_user_session_path %></span>
      <% end %>
    </div>
  </div>
</div>