config/routes.rb
Rails.application.routes.draw do

  namespace :profile do
    resources :users, only: :show
  end

  get 'dashboards/show'

  devise_for :users,
    controllers: {
                    omniauth_callbacks: 'users/omniauth_callbacks',
                    registrations: 'registrations'
                 }

  resources :meetings do
    resources :bookings do
      member do
        patch "confirm_user"
      end
    end
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @nb_booking = @user.booking.count
    @nb_meeting_mentor = @user.meetings.count
    @nb_meeting_mentee = @user.booking.count
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper

  def mentee_message                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          (meeting)
    mentee_confirmed = meeting.booking.reduce(0){|counter, item| counter += (item.confirmation == true ? 1 : 0)}
    mentee_pending = meeting.booking.reduce(0){|counter, item| counter += (item.confirmation == true ? 0 : 1)}
    if mentee_confirmed < meeting.nb_max_participant
      "Mentees: #{mentee_confirmed} confirmed / #{mentee_pending} pending"
    else
      "Max number of participants reached"
    end

  end
end

app/views/dashboards/show.html.erb
<!-- Lateral card with profile main info -->
<div class="container">
<div class="row padding-sup">
  <!-- add image_tag @user.avatar_url -->

  <div class="col-xs-3">
    <div class="text-center card card-profile">
    <div class="header-image" style="background-image: url('https://unsplash.it/600/120')"></div>
    <%= link_to profile_user_path(@user) do %>
      <div class='div-center'><%= image_tag @user.avatar_url%></div>
    <% end %>
    <div class="content text-center">
      <h4><%= "#{@user.first_name} #{@user.last_name}"%></h4><br>
      <h6><%=@user.industry%></h6>
      <h6><%=@user.profile %></h6>
      <hr>
      <h5>Your meetings as mentee:</h5>
      <%=@nb_meeting_mentee%>
      <hr>
      <h5>Your meetings as mentor:</h5>
      <%=@nb_meeting_mentor%> <br>
    </div>
    </div>
  </div>

  <!-- List of meeting as mentee -->
  <% if @nb_booking > 0 %>
  <div class="col-xs-9">
    <div class="row">
    <div class="col-xs-12">
      <h3>Your mentors and event - you as a mentee</h3>
    </div>
    </div>
    <div class="row">
    <div class="card card-list">
      <hr>
      <%@user.booking.each do |booking|%>
      <div class="row list-div">
        <div class="col-xs-4">
          <div class="dash-flex">
            <div class='div-center'>
              <%= link_to profile_user_path(booking.meeting.user) do %>
                <%= image_tag booking.meeting.user.avatar_url%>
              <% end %>
            </div>
            <div class="dash-title">
             <%="#{booking.meeting.user.first_name} #{booking.meeting.user.last_name}"%><br>
              <h6><%="#{booking.meeting.user.industry} | #{booking.meeting.user.profile}"%></h6>
            </div>
          </div>
        </div>

        <div class="col-xs-6">
          <%= link_to meeting_path(booking.meeting) do %>
            <div class="no-decoration">
              <strong><%=booking.meeting.title%></strong><br>
              <%=booking.meeting.profile_wanted%><br>
              <i class="fa fa-calendar"></i><%=" #{booking.meeting.date.strftime('%d %b, %Y')} | #{booking.meeting.date.strftime('%I:%M%P')}"%> <br>
              <i class="fa fa-map-marker"></i><%=" #{booking.meeting.local}"%>
            </div>
          <% end %>
        </div>
        <div class="col-xs-2 text-center">
          <% if booking.confirmation%>
            <h6>Your participation has been confirmed</h6>
            <%= image_tag 'green-light.png', id: "light"%>
          <% else %>
            <h6>Confirmation pending</h6>
            <%= image_tag 'red-light.png', id: "light"%>
          <% end %>
        </div>
      </div>
      <hr>
      <% end %>
    </div>
    </div>
  <%end%>

  <!-- List of meeting as mentor -->
  <% unless @user.meetings.count == 0 %>
    <div class="row">
    <div class="col-xs-12">
      <h3>Your mentorship event - you as a mentor</h3>
    </div>
    </div>
    <div class="row">
    <div class="card card-list">
      <hr>
      <%@user.meetings.each do |meeting|%>
      <div class="row list-div">
        <div class="col-xs-8">
        <div class="list-pad">
          <%= link_to meeting_path(meeting) do %>
            <div class="no-decoration">
              <strong><%=meeting.title%></strong><br>
              <p><%=meeting.profile_wanted%></p>
              <i class="fa fa-calendar"></i><%=" #{meeting.date.strftime('%d %b, %Y')} | "%>
              <i class="fa fa-map-marker"></i><%=" #{meeting.local}"%>
            </div>

          <% end %>
        </div>
        </div>
        <div class="col-xs-4">
          <div class="row">
            <%= mentee_message(meeting)%>
          </div>
          <div class="row">
            <% meeting.booking.each do |booking|%>
              <% if booking.confirmation%>
                <%= link_to profile_user_path(booking.user) do %>
                  <%= image_tag booking.user.avatar_url, class: "preview"%>
                <% end %>
             <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <hr>
      <% end %>
    </div>
    </div>
  <% end %>

  </div>
</div>
</div>